import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Login from '../components/LoginComponent'
import { useEffect } from 'react';
import { useSelector } from 'react-redux'
import { useRouter } from "next/router";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const user = useSelector((state)=>state?.user?.currentUser);
  const router = useRouter();
  useEffect(()=>{
      if(user){
          router.push("/chats");
      }
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          background:
            "url(https://images.unsplash.com/photo-1672872476232-da16b45c9001?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1471&q=80)",
        }}
        className={`${styles.main} flex h-screen items-center justify-center`}
      >
        <Login />
      </main>
    </>
  );
}
